# Beer Reviews

In [56]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
import translators as ts
import missingno as msno
import warnings
import autoreload
import os
import sys
import csv

from collections import defaultdict, Counter

from sklearn.impute import SimpleImputer

sb.set_style('darkgrid')
sb.set_palette('viridis')

pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 1000)

%matplotlib inline
plt.rcParams.update({'font.size':14})

warnings.filterwarnings('ignore')

In [49]:
df = pd.read_csv(r"D:\Open Classroom\Datasets\NLP for German News Articles\Posts.csv")
df.head()

,ID_Post,ID_Parent_Post,ID_Article,ID_User,CreatedAt,Status,Headline,Body,PositiveVotes,NegativeVotes
0,1,NaN,1,9089,2003-04-23 14:52:41.870,deleted,NaN,NaN,0,0
1,2,NaN,1,29367,2003-11-04 16:21:57.850,online,"Newsletter ""DER STANDARD""",Ich bin begeistert von den STANDARD - Newslett...,0,0
2,3,2.0,1,5095,2004-01-28 12:57:28.240,deleted,Auch begeistert...,... Aber momentan funktioniert das Abmelden od...,0,0
3,4,3.0,1,1682,2004-02-03 20:32:39.123,deleted,Abmeldeprobleme,Es ist ganz einfach nervend!\r\nVor kurzem hab...,0,0
4,5,NaN,1,3343,2004-03-02 11:37:44.100,online,NaN,und sie als mitarbeiter sind natuerlich objektiv,0,0