In [26]:
import pandas as pd

In [27]:
df = pd.read_csv(r"D:\Open Classroom\Data Files\week2\week2\richmond_collisions.csv")
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 300)
df.head()#.style.background_gradient(cmap = "Reds")

,CASEID,POINT_X,POINT_Y,YEAR_,LOCATION,CHPTYPE,DAYWEEK,CRASHSEV,VIOLCAT,KILLED,INJURED,WEATHER1,PEDCOL,BICCOL,MCCOL,TRUCKCOL,ETOH,TIMECAT,MONTH_,CRASHTYP,INVOLVE,PED,PRIMARYRD,SECONDRD,DISTANCE,DIRECT,INTERSECT_,PROCDATE,JURIS,DATE_,TIME_,BADGE,JURIDIST,SHIFT,POP,SPECIAL,BEATTYPE,LAPDDIV,BEATCLAS,BEATNUMB,WEATHER2,STATEHW,CALTRANC,CALTRAND,STROUTE,ROUTESUF,POSTPRE,POSTMILE,LOCATYPE,RAMP,SIDEHW,TOWAWAY,PARTIES,PCF,VIOLCODE,VIOL,VIOLSUB,HITRUN,ROADSURF,RDCOND1,RDCOND2,LIGHTING,RIGHTWAY,CHPRDTYP,NOTPRIV,STFAULT,CHPFAULT,SEVINJ,OTHERINJ,COP,PEDKILL,PEDINJ,BICKILL,BICINJ,MCKILL,MCINJURE,RAMP1,RAMP2,CITY,COUNTY,STATE,X_CHP,Y_CHP
0,1785833,-122.337733,37.976154,2005,710,0,6,3,09,0,1,B,NaN,NaN,NaN,NaN,NaN,2400,1,D,C,A,ROBERT H MILLER,BIRMINGHAM AV,0,NaN,Y,2005-06-03,710,2005-01-01,2100,1220,NaN,5,5,0,0,NaN,0,NaN,C,N,NaN,0,0,NaN,NaN,0.00,NaN,NaN,NaN,Y,2,A,-,21802,A,M,B,H,-,C,A,0,Y,-,-,0,1,0,0,0,0,0,0,0,-,-,RICHMOND,CONTRA COSTA,CA,0.0,0.0
1,1785837,-122.344543,37.939667,2005,710,0,7,4,09,0,2,B,NaN,NaN,NaN,NaN,NaN,1200,1,D,C,A,ROOSEVELT AV,25TH ST,0,NaN,Y,2005-05-26,710,2005-01-02,1135,1242,NaN,5,5,0,0,NaN,0,NaN,C,N,NaN,0,0,NaN,NaN,0.00,NaN,NaN,NaN,Y,2,A,-,21800,A,N,B,H,-,A,A,0,Y,A,NaN,0,0,2,0,0,0,0,0,0,-,-,RICHMOND,CONTRA COSTA,CA,0.0,0.0
2,1785883,-122.347521,37.941422,2005,710,0,6,4,09,0,1,C,NaN,NaN,NaN,NaN,NaN,1500,1,D,C,A,23RD ST,GRANT AV,6,N,N,2005-06-03,710,2005-01-01,1300,1401,NE,5,5,0,0,NaN,0,010,-,N,NaN,0,0,NaN,NaN,0.00,NaN,NaN,NaN,N,2,A,-,21802,A,N,B,H,-,A,A,0,Y,A,NaN,0,0,1,0,0,0,0,0,0,-,-,RICHMOND,CONTRA COSTA,CA,0.0,0.0
3,1785899,-122.323523,37.914116,2005,710,0,7,4,12,0,2,B,NaN,NaN,NaN,NaN,NaN,1500,1,D,C,A,CARLSON BL,BAYVIEW AV,0,NaN,Y,2005-06-15,710,2005-01-02,1435,1220,NaN,5,5,0,0,NaN,0,NaN,C,N,NaN,0,0,NaN,NaN,0.00,NaN,NaN,NaN,Y,4,A,-,21453,A,N,B,H,-,A,A,0,Y,-,-,0,0,2,0,0,0,0,0,0,-,-,RICHMOND,CONTRA COSTA,CA,0.0,0.0
4,1830750,-122.324561,37.940150,2005,710,1,7,4,18,0,1,B,NaN,NaN,NaN,NaN,NaN,1500,1,E,J,A,RT 80,SAN PABLO AV,1056,E,N,2005-08-04,9370,2005-01-02,1438,01721,NaN,2,5,0,1,NaN,2,082,C,Y,CC,4,80,-,-,3.19,H,-,E,N,1,C,-,0,NaN,N,B,H,-,A,D,6,Y,-,-,0,0,1,0,0,0,0,0,0,-,-,RICHMOND,CONTRA COSTA,CA,0.0,0.0

In [28]:
df.set_index(df["TIME_"], inplace = True)
#df = df.dropna(axis = "index", how = "any")

In [29]:
df.head()

,CASEID,POINT_X,POINT_Y,YEAR_,LOCATION,CHPTYPE,DAYWEEK,CRASHSEV,VIOLCAT,KILLED,INJURED,WEATHER1,PEDCOL,BICCOL,MCCOL,TRUCKCOL,ETOH,TIMECAT,MONTH_,CRASHTYP,INVOLVE,PED,PRIMARYRD,SECONDRD,DISTANCE,DIRECT,INTERSECT_,PROCDATE,JURIS,DATE_,TIME_,BADGE,JURIDIST,SHIFT,POP,SPECIAL,BEATTYPE,LAPDDIV,BEATCLAS,BEATNUMB,WEATHER2,STATEHW,CALTRANC,CALTRAND,STROUTE,ROUTESUF,POSTPRE,POSTMILE,LOCATYPE,RAMP,SIDEHW,TOWAWAY,PARTIES,PCF,VIOLCODE,VIOL,VIOLSUB,HITRUN,ROADSURF,RDCOND1,RDCOND2,LIGHTING,RIGHTWAY,CHPRDTYP,NOTPRIV,STFAULT,CHPFAULT,SEVINJ,OTHERINJ,COP,PEDKILL,PEDINJ,BICKILL,BICINJ,MCKILL,MCINJURE,RAMP1,RAMP2,CITY,COUNTY,STATE,X_CHP,Y_CHP
TIME_,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2100,1785833,-122.337733,37.976154,2005,710,0,6,3,09,0,1,B,NaN,NaN,NaN,NaN,NaN,2400,1,D,C,A,ROBERT H MILLER,BIRMINGHAM AV,0,NaN,Y,2005-06-03,710,2005-01-01,2100,1220,NaN,5,5,0,0,NaN,0,NaN,C,N,NaN,0,0,NaN,NaN,0.00,NaN,NaN,NaN,Y,2,A,-,21802,A,M,B,H,-,C,A,0,Y,-,-,0,1,0,0,0,0,0,0,0,-,-,RICHMOND,CONTRA COSTA,CA,0.0,0.0
1135,1785837,-122.344543,37.939667,2005,710,0,7,4,09,0,2,B,NaN,NaN,NaN,NaN,NaN,1200,1,D,C,A,ROOSEVELT AV,25TH ST,0,NaN,Y,2005-05-26,710,2005-01-02,1135,1242,NaN,5,5,0,0,NaN,0,NaN,C,N,NaN,0,0,NaN,NaN,0.00,NaN,NaN,NaN,Y,2,A,-,21800,A,N,B,H,-,A,A,0,Y,A,NaN,0,0,2,0,0,0,0,0,0,-,-,RICHMOND,CONTRA COSTA,CA,0.0,0.0
1300,1785883,-122.347521,37.941422,2005,710,0,6,4,09,0,1,C,NaN,NaN,NaN,NaN,NaN,1500,1,D,C,A,23RD ST,GRANT AV,6,N,N,2005-06-03,710,2005-01-01,1300,1401,NE,5,5,0,0,NaN,0,010,-,N,NaN,0,0,NaN,NaN,0.00,NaN,NaN,NaN,N,2,A,-,21802,A,N,B,H,-,A,A,0,Y,A,NaN,0,0,1,0,0,0,0,0,0,-,-,RICHMOND,CONTRA COSTA,CA,0.0,0.0
1435,1785899,-122.323523,37.914116,2005,710,0,7,4,12,0,2,B,NaN,NaN,NaN,NaN,NaN,1500,1,D,C,A,CARLSON BL,BAYVIEW AV,0,NaN,Y,2005-06-15,710,2005-01-02,1435,1220,NaN,5,5,0,0,NaN,0,NaN,C,N,NaN,0,0,NaN,NaN,0.00,NaN,NaN,NaN,Y,4,A,-,21453,A,N,B,H,-,A,A,0,Y,-,-,0,0,2,0,0,0,0,0,0,-,-,RICHMOND,CONTRA COSTA,CA,0.0,0.0
1438,1830750,-122.324561,37.940150,2005,710,1,7,4,18,0,1,B,NaN,NaN,NaN,NaN,NaN,1500,1,E,J,A,RT 80,SAN PABLO AV,1056,E,N,2005-08-04,9370,2005-01-02,1438,01721,NaN,2,5,0,1,NaN,2,082,C,Y,CC,4,80,-,-,3.19,H,-,E,N,1,C,-,0,NaN,N,B,H,-,A,D,6,Y,-,-,0,0,1,0,0,0,0,0,0,-,-,RICHMOND,CONTRA COSTA,CA,0.0,0.0

In [30]:
df.reset_index(inplace = True)
df["TIME"] = df["TIME_"].astype(str).str.get(0) + df["TIME_"].astype(str).str.get(1) + ":" + df["TIME_"].astype(str).str.get(2) + df["TIME_"].astype(str).str.get(3)
#df.drop(columns = ["DATETIME"], inplace = True)
df.head()

ValueError: cannot insert TIME_, already exists

In [ ]:
df["DATETIME"] = df["DATE_"] + " " + df["TIME"].astype(str)
df.head()

In [ ]:
df["DATETIME"] = pd.to_datetime(df["DATETIME"], format = "%Y-%m-%d %I")